### PR TITLE
ENH: Set path to source for coverage tests

### PR DESCRIPTION
**Pull request by cookpa**
Hoping this lets the coveralls successfully find the source files

### CODE REVIEW

**Comment by cookpa** [comment]
Looks like this didn't help, it just made the output more annoying to read by including the whole source tree to the installed package. Still not able to view the source

image

**Comment by cookpa** [comment]
Doh - further googling reveals the source is only available if the user is signed in.

**Comment by ncullen93** [comment]
It should be working now. It works for me, anyways. I just had to sign in and then set the github repo root directory to everything up to ".../site-packages/" 

Screen Shot 2024-02-19 at 12 53 27 AM

**Comment by ncullen93** [comment]
Now if I click List and then any file:

Screen Shot 2024-02-19 at 1 00 03 AM

**Comment by cookpa** [comment]
Thanks @ncullen93 - I see the source now.

**Pull request closed without merging**
