### PR TITLE
add SimpleITK.Image to ANTsImage conversion

### PR DESCRIPTION
**Pull request by dyollb**
- add helper function to get an ANTsImage from a [SimpleITK.Image](https://simpleitk.readthedocs.io/en/master/fundamentalConcepts.html#images)
- add test that does the roundtrip

### CODE REVIEW

**Comment by dyollb** [comment]
I guess the coverage went down because the test doesn't run unless SimpleITK is installed. Should I install it in the CI?

**Comment by dyollb** [comment]
> This looks very useful. We have other functions like from_numpy() so maybe we should name similarly, eg from_sitk(sitk image) and to_sitk(ANTsImage)?

would you also rename the module?

**Comment by cookpa** [comment]
This is shaping up, @dyollb would you mind editing `ants/utils/__init__.py` to import the functions, so they can be called as `ants.from_sitk` etc

**Comment by cookpa** [comment]
This LGTM, thanks

**Pull request merged**
