### PR TITLE
ENH: Bump ANTs version to read Windows pointers

### PR DESCRIPTION
**Pull request by cookpa**
Need someone to try out the windows wheels

### CODE REVIEW

**Comment by cookpa** [comment]
A simple registration test would do it - if the images can be read, it means it worked.

ANTs was only attempting to parse pointers if they started with "0x". Windows pointers seem to just start with "0", you can see this in ITK Exceptions thrown on Windows. I'm hoping that if these are recognized and parsed as pointers, the images will get loaded.

**Comment by ntustison** [comment]
Thanks for this, @cookpa .  A student I'm working with just came across this issue yesterday.  I'm seeing if they can test it out.

**Comment by ntustison** [comment]
Hey @cookpa , @wdgstl agreed to test it out.  I'm going to be over in Santa Monica this morning but I'll be back to monitor this thread and help out where I can.  Thanks to you both.

**Comment by cookpa** [comment]
Great, I'll update when the wheels are ready

**Comment by cookpa** [comment]
Hi @wdgstl , build artifacts are here 

https://github.com/ANTsX/ANTsPy/suites/11633439300/artifacts/603943952

Sorry it's a huge download - the zip should contain all the wheels.

Thanks for helping with this!

**Comment by cookpa** [comment]
@wdgstl, @ntustison Individual wheels are now available

https://github.com/ANTsX/ANTsPy/actions/runs/4478997465

**Comment by wdgstl** [comment]
@cookpa what are the next steps after installing the proper build wheels?

**Comment by wdgstl** [comment]
@ntustison I'm still getting the same error after installing the wheels

**Comment by cookpa** [comment]
This one will hopefully work https://github.com/ANTsX/ANTsPy/actions/runs/4481220355

**Comment by cookpa** [comment]
OK I think I'm getting somewhere and can now test independently - will update later. Thanks again

**Comment by cookpa** [comment]
Superceded by #224

**Pull request closed without merging**
