### PR TITLE
ENH: Update coveralls version

### PR DESCRIPTION
**Pull request by cookpa**
Bumping the version, hoping to avoid coverage errors.

On coveralls.io, docstrings are being interpreted as uncovered code. This seems to only be a problem on multi-line function definitions.

https://coveralls.io/builds/66464549/source?filename=home%2Frunner%2F.local%2Flib%2Fpython3.10%2Fsite-packages%2Fants%2Fsegmentation%2Fatropos.py

I don't see this issue on my local machine if I run the tests

### CODE REVIEW

**Comment by cookpa** [comment]
Didn't help, it's still counting docstrings. Doesn't happen on my mac with the same coverage version (7.4.4).

**Comment by ncullen93** [comment]
Ah weird... is a docstring supposed to be a ' instead of " ?  Maybe that will help.

**Comment by cookpa** [comment]
I think they are supposed to be double quotes - I might try exporting the coverage results to XML

**Comment by cookpa** [comment]
OK XML worked. It looks correct now

**Pull request merged**
