### PR TITLE
ENH:  Add b-spline fitting.

### PR DESCRIPTION
**Pull request by ntustison**

### CODE REVIEW

**Comment by ntustison** [comment]
Hey @stnava it looks like the circle ci check is simply timing out.  Has that been your experience?

**Comment by stnava** [comment]
I haven't seen timeouts with circle ci before ...

**Comment by stnava** [comment]
also - do you mind adding tests for these new adds?  they are also good examples of usage.

**Comment by stnava** [comment]
https://github.com/ANTsX/ANTsPy/tree/master/tests

**Comment by ntustison** [comment]
Okay I'll do some more digging.  A previous encounter with this was remedied by simply re-running the Circle CI check and the most current encounter said something like "Exiting because of zero timed output" or something like that.  

I didn't know about the tests but I can certainly transplant the examples.

**Comment by ntustison** [comment]
Just copying and pasting the actual message for reference.

Screen Shot 2020-05-01 at 9 01 25 AM

**Comment by ntustison** [comment]
Compilation for ImageMathHelper might be the culprit.

**Comment by stnava** [comment]
first priority for tests here are mainly to make sure the code runs w/o fault then 2nd to test for correctness .....

I updated the circleci config s.t. it should allow longer build - you probably need to rebase on master

**Comment by ntustison** [comment]
Now it looks like it's running into Cmake issues.  Very odd.

**Comment by stnava** [comment]
it's my fault - I updated the python docker and that's caused problems ---- will update again

**Comment by stnava** [comment]
they don't let you clear the cache easily ...

**Comment by ntustison** [comment]
Thanks.  As soon as we get these two pull requests merged, I'll work on the tests.

**Comment by stnava** [comment]
guess will merge - circle-ci looks like a compiler out of memory error

**Comment by ntustison** [comment]
Great.  Thanks.  I'll work on the tests after my run today.

**Pull request merged**
