### PR TITLE
revise ortho plot direction, failed setup from github source

### PR DESCRIPTION
**Pull request by qinqian**
I tried to make a quick fix on issue(the https://github.com/ANTsX/ANTsPy/issues/59). However, I cannot make a thorough test since I cannot use "python setup.py install" to install ANTsPy, I tried to add -std=c++1y and -std=c++11 in cmake file, but neither worked. Previously, I can install ANTsPy by using pip. I am using ANTspy with Ubuntu 16.04 and python3.6. Thanks.

### CODE REVIEW

**Comment by qinqian** [comment]
WIthout -std=c++1y or -std=c++11 in ants/lib/CMakeLists.txt, the setup failed with a nullptr error. With either option, the setup failed with the following error:

     mutualInformationMetric->SetUseSampledPointSet( false );
           ^
cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’

**Comment by qinqian** [comment]
This installation issue is actually caused by network connection failure, it is fixed now.

**Comment by stnava** [comment]
if you don't mind, I will cherry pick the plot update and try it out ... otherwise, please just make a new pull request with only your requested changes to the plot function.

**Comment by stnava** [comment]
https://github.com/ANTsX/ANTsPy/commit/826f096351f7cf6b8575737d454acb14387809ef

**Comment by qinqian** [comment]
Sure, I don't mind. Thank you for maintaining such a great package.

**Pull request closed without merging**
