### PR TITLE
antspy to v0.5.0 and bump ants + itk versions to latest commit hashes

### PR DESCRIPTION
**Pull request by ncullen93**
Bumps antspy to v0.5.0 and use the latest ants and itk commit hashes for building. We'll see if it's this simple...

Eventual general release notes:

- improved testing 
- minor bug fixes
- minor documentation improvements
- upgrade to latest ANTs and ITK version
- removed deprecated code (VTK-related visualization)

Things to accomplish during v0.5.x
- rework docs and tutorials (to ants.dev)
- reduce build size
- refactor ants.plot function to be simpler
- speed up import time (by deferring imports?)

### CODE REVIEW

**Comment by cookpa** [comment]
This looks great, thanks @ncullen93 

To avoid confusion in the future, could we reserve vX.Y.Z for tags of release commits, and use vX.Y.Z-dev or something for branch names?

**Comment by ncullen93** [comment]
That'd be great but how would it work exactly? On the main branch it will always be "X.Y.Z-dev" and then when it's time for a release we just remove the "-dev", publish the release, and then add it back?

Also - it looks like the linux action failed to publish to pypi when you merged because the package size was too large... so I'm  not sure if it has been updated on pypi?

**Comment by cookpa** [comment]
> That'd be great but how would it work exactly? On the main branch it will always be "X.Y.Z-dev" and then when it's time for a release we just remove the "-dev", publish the release, and then add it back?

I was thinking we'd make a vX.Y.Z-dev branch, and push commits to it until we're ready, then merge back into main, tag HEAD with vX.Y.Z, and then hit release.

**Comment by gdevenyi** [comment]
Here's the ref for the official way to name development releases in Python
https://peps.python.org/pep-0440/#development-release-separators

**Comment by cookpa** [comment]
Open to changing things to be more pythonic, but what I was trying to suggest here is that we avoid having a branch and a tag with the same label. It's technically allowed by Git but I am easily confused

**Comment by ntustison** [comment]
@ncullen93 @cookpa --- how should we update this with respect to the recent KK change?

**Comment by cookpa** [comment]
I think a bug fix release would be in order

**Comment by ncullen93** [comment]
I'm fine with whatever but I prefer making changes on the main branch. People probably expect the main branch to be the most up-to-date version of the code.  Then making the version in setup.py / the actual package "vX.Y.Z-dev" would make sense.

**Comment by cookpa** [comment]
Agreed 100%, making PRs and then merging to master incrementally is the way to go. The release branches should just be like this PR, for doing release finalization. I just don't want to confuse the _tag_ v0.5.0 on the master branch, with the v0.5.0 branch itself. But if we clean up the release PR branches as we go, then  I suppose the risk is pretty minimal. I'm going to delete the branch now as the site is prompting me.

Regarding dev release numbers in the code, ITK does something like this, the code for which was adapted into ANTs, it sets the version on compile to something other than the last release tag, so we can tell if someone is using the actual tag commit or some commit between tags. This only works correctly if built from a cloned git repo, because it uses git to figure out the commit it's being built from. Might be nice to have - but we need to have a sensible fallback (eg, to the hard-coded previous release tag).

**Pull request merged**
